version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      # - ./:/app
    ports:
      - 127.0.0.1:${MYSQL_PORT}:3306
  apache:
    image: pswerlang/php-apache
    volumes:
      - ./public_html:/var/www/html
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: always
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx:/etc/nginx/conf.d
    environment:
        - SITES=${URL}=apache
        - FORCE_HTTPS=true
volumes:
  mysql: