version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      # - ./:/app
    ports:
      - 127.0.0.1:3306:3306
  apache:
    image: pswerlang/php-apache
    volumes:
      - ./public_html:/var/www/html
    ports:
      - 80:80
volumes:
  mysql: